tracker_type: bytetrack
track_high_thresh: 0.08
track_low_thresh: 0.1
new_track_thresh: 0.95
track_buffer: 20000
match_thresh: 0.2
fuse_score: true
gmc_method: sparseOptFlow
proximity_thresh: 0.3
appearance_thresh: 0.2
with_reid: false
model: auto